import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import page from "./static-page/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar></AppBar>
        {children}</body>
    </html>
  );
}

 
// export function Page() {
//   return <Link href="/static-page"></Link>
// }

function AppBar(){
  return <div>
  <div className="flex justify-center m-20">
      <div className="flex ">
        <Link href="/">
        <button type="button" className="m-10 text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 ">Home</button>

        </Link>
        <Link href="/interactive-page">
       <button type="button" className="m-10 text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 ">Server Page</button>
   
       </Link>
       <Link href="/static-page">
          <button type="button"  className="m-10 text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 ">Client Page</button>
   
        </Link>
          </div>
  
  </div>
 
</div>
}
